import React, { Component } from 'react';
//import {Dropdown} from 'semantic-ui-react';
import Select from 'react-select'

import 'react-virtualized/styles.css'
import 'react-virtualized-select/styles.css'
import DatePicker from 'react-datepicker'
import "react-datepicker/dist/react-datepicker.css"



class Report extends Component {
    state = {
      
        selectedUserOption: null,

        countryOptions: [
            { key: 'af', value: 'af', flag: 'af', text: 'Afghanistan' },
            { key: 'ax', value: 'ax', flag: 'ax', text: 'Aland Islands' },
            { key: 'al', value: 'al', flag: 'al', text: 'Albania' },
            { key: 'dz', value: 'dz', flag: 'dz', text: 'Algeria' },
            { key: 'as', value: 'as', flag: 'as', text: 'American Samoa' },
            { key: 'ad', value: 'ad', flag: 'ad', text: 'Andorra' },
            { key: 'ao', value: 'ao', flag: 'ao', text: 'Angola' },
            { key: 'ai', value: 'ai', flag: 'ai', text: 'Anguilla' },
            { key: 'ag', value: 'ag', flag: 'ag', text: 'Antigua' },
            { key: 'ar', value: 'ar', flag: 'ar', text: 'Argentina' },
            { key: 'am', value: 'am', flag: 'am', text: 'Armenia' },
            { key: 'aw', value: 'aw', flag: 'aw', text: 'Aruba' },
            { key: 'au', value: 'au', flag: 'au', text: 'Australia' },
            { key: 'at', value: 'at', flag: 'at', text: 'Austria' },
            { key: 'az', value: 'az', flag: 'az', text: 'Azerbaijan' },
            { key: 'bs', value: 'bs', flag: 'bs', text: 'Bahamas' },
            { key: 'bh', value: 'bh', flag: 'bh', text: 'Bahrain' },
            { key: 'bd', value: 'bd', flag: 'bd', text: 'Bangladesh' },
            { key: 'bb', value: 'bb', flag: 'bb', text: 'Barbados' },
            { key: 'by', value: 'by', flag: 'by', text: 'Belarus' },
            { key: 'be', value: 'be', flag: 'be', text: 'Belgium' },
            { key: 'bz', value: 'bz', flag: 'bz', text: 'Belize' },
            { key: 'bj', value: 'bj', flag: 'bj', text: 'Benin' },
          ],
          date: new Date()

      }



    render() { 
        return ( 

            <div>
                <h1>Report Page</h1>

                <div className="form-inline  form-group justify-content-center">
                
                <div style={{width:'10%'}} >
                  <Select   
                  className="search"
                  placeholder='Select User'
                  value="af"
                  options={this.state.countryOptions}/>  
                </div>
                
                <div>
                  <DatePicker
                  placeholderText="From"
                  name="fromDate"
                  id="fromDate"
                  value= {this.state.date} 
                  className="form-control datepicker"/> 
                </div>

                <div>
                <DatePicker
                  placeholderText="To"
                  name="toDate"
                  id="toDate"
                  value= {this.state.date} 
                  className="form-control datepicker"/> 
                </div>
               
                </div>


                <table className="table">
                        <thead className="thead-dark">
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">License Plate Number</th>
                            <th scope="col">Generated by:</th>
                            <th scope="col">Generated on:</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr key='1'>
                                <th scope="row">#</th>
                                <td>ALS001GH</td>
                                <td>Salau Yusuf</td>
                                 <td>12/12/2018</td>
                            </tr>
                            <tr key='1'>
                                <th scope="row">#</th>
                                <td>ALS00ER</td>
                                <td>Salau Yusuf</td>
                                 <td>12/12/2018</td>
                            </tr>

                            {/* {this.state.priceList.map((el, index)=>{
                                if(el.activeStatus === true){
                                    return (
                                        <tr key={el._id}>
                                        <th scope="row">{index+1}</th>
                                        <td>{el.productGroup}</td>
                                        <td>{el.name}</td>
                                        <td>{el.price}</td>
                                        </tr>)
                                }else{
                                    return (
                                            <tr key={el._id}style={{textDecoration:"line-through", color:'grey'}}>
                                            <th scope="row">#</th>
                                            <td>{el.productGroup}</td>
                                            <td>{el.name}</td>
                                            <td>{el.price}</td>
                                            </tr>)
                                    
                                }
                                
                            })} */}

                        </tbody>
                        </table>
            </div>

         );
    }
}
 
export default Report;